# Generated by Django 5.2.4 on 2025-08-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='progress_percebt',
            new_name='progress_percent',
        ),
    ]
